### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by germaino** [logzio/jaeger-logzio#18]
Can you please clarify how to use it ?
I am expecting the collector to read jaeger traces from an endpoint and write them to logzio account.
thanks

**Comment by yyyogev** [comment]
Hi @germaino 
Our Jaeger integration works exactly like the regular all-in-one jaeger client except for the logz.io credentinials which explained thoroughly in our readme. 
 if you still have any issues you are more than welcome to contact ourIf you still have any issues you are more than welcome to contact our support team
